FROM python:3.11

RUN pip install pandas
RUN pip install scipy
RUN pip install scikit-learn
RUN pip install requests
RUN pip install sqlalchemy
RUN pip install sqlalchemy_utils
RUN pip install psycopg2-binary 
